import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { authOptions } from "@/lib/authOptions";
import { getServerSession } from "next-auth";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          {session && <Navbar />}
          {!session && (
            <div className=" flex items-center justify-center ">
              <Login />
            </div>
          )}
          <div className="container my-6">{children}</div>
          <Toaster richColors />
        </body>
      </html>
    </AuthProvider>
  );
}
